---
kind: pipeline
name: checkups
workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

steps:
  # check dependencies
  - dependancies:
    name: dependancies
    image: cblomart/gobasebuild
    commands:
    - go version
    - go generate ./...
    - tags=$(git rev-parse --short HEAD)
    - if [ ! -z "$DRONE_TAG" ]; then tags="$tags,$DRONE_TAG,latest"; fi
    - echo $tags | tee .tags
  # do the checkups
  - checkups:
    name: checks
    image: cblomart/gobasebuild
    commands:
    - staticcheck -f stylish ./...
    - gofmt -s -d .
    - go vet ./...
    - golint ./...
    - ineffassign ./
    - gosec ./...
